jidelni_listek/urls.py
from django.conf.urls import url, include, patterns


from jidelni_listek import views

app_name='jidelni_listek'
urlpatterns = patterns('jidelni_listek.views', 
    url(r'^$', 'index'),
    url(r'^(?P<list_id>[0-9]+)/$', views.detail, name='detail'),
)

photogallery/urls.py
from django.conf.urls import *
from .views import PhotoJSONListView
from photologue.views import GalleryListView
from django.views.generic import TemplateView

urlpatterns = patterns('',

						url(r'^gallerylist/$', GalleryListView.as_view(), name='photogallery-gallery-list'),
						url(r'^photolist/$', PhotoJSONListView.as_view(), name='photogallery-photo-json-list'),
                       )

jidelni_listek/models.py
# coding: utf-8

from django.db import models
from django.utils import timezone
from datetime import datetime, timedelta
from adminsortable.fields import SortableForeignKey
from adminsortable.models import SortableMixin

class Product(SortableMixin):
    product_name = models.CharField('Název', max_length=200)
    amount = models.CharField('Množství', max_length=11)
    product_price = models.CharField('Cena', default=0, max_length=14)
    lists = models.ManyToManyField('List', blank=True, verbose_name='Patří do lístku')
    product_type = models.ForeignKey('Type', blank=True, verbose_name='Typ')
    pub_date = models.DateTimeField('Platnost od', default=timezone.now())  
    plist = models.ForeignKey('self', related_name='+', blank=True, limit_choices_to={'product_type__name': 'Pivo'}, verbose_name='Doporučené pivo', null=True, default="")
    vlist = models.ForeignKey('self', related_name='+', blank=True, limit_choices_to={'product_type__name': 'Víno'}, verbose_name='Doporučené víno', null=True, default="")
    product_description = models.TextField('Popis', blank=True)

    # ordering field
    product_order = models.PositiveIntegerField(default=0, editable=False, db_index=True)


    def __unicode__(self):
        return '%s (%s)' % (self.product_name, self.amount)

    class Meta:
        verbose_name = 'Produkt'
        verbose_name_plural = 'Produkty'
        ordering = ['product_order']



class Type(SortableMixin):
    name = models.CharField('Název', max_length=100)
    products = models.ManyToManyField(Product, verbose_name='Produkty', blank=True)
    lists = models.ManyToManyField('List', verbose_name='Lístky', blank=True)
    # ordering field
    type_order = models.PositiveIntegerField(default=0, editable=False, db_index=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = 'Kategorie'
        verbose_name_plural = 'Kategorie'
        ordering = ['type_order']

class List(SortableMixin):
    name = models.CharField('Název jídelního lístku', max_length=100)
    products = models.ManyToManyField(Product, blank=True, through=Product.lists.through)
    list_short_description = models.CharField('Krátký popis lístku', max_length=100, blank=True)
    list_long_description = models.TextField('Dlouhý popis lístku', blank=True)
    icon = models.CharField('Ikona', max_length=50, choices=(('tree', 'Strom'), ('cutlery', 'Příbor'), ('birthday-cake', 'Dort'), ('heart', 'Srdce'), ('coffee', 'Hrnek'), ('glass', 'Sklenka'), ('sun-o', 'Slunce'), ('star', 'Hvězda'), ('music', 'Hudba'), ('hourglass-half', 'Poledne')))
    bottom_line_description = models.TextField('Popis u spodní části menu', blank=True)
    types_in_list = models.ManyToManyField(Type)
    special = models.BooleanField('Speciální nabídka', default=False)
    experience = models.BooleanField('Zážitkové menu', default=False) 
    wine = models.BooleanField('Vinný list', default=False)
    
    # ordering field 
    list_order = models.PositiveIntegerField(default=0, editable=False, db_index=True)

    @property
    def sorted_products(self):
        return self.products.all().order_by('product_type', 'product_order')

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = 'Lístek'
        verbose_name_plural = 'Lístky'
        ordering = ['list_order']

class PoledniMenu(models.Model):
    name = models.CharField('Polední menu', max_length=30, default='Polední menu')
    list_long_description = models.TextField('Dlouhý popis lístku', blank=True)
    icon = models.CharField('Ikona', max_length=50, choices=(('hourglass-half', 'Poledne'), ('cutlery', 'Příbor')))
    bottom_line_description = models.TextField('Popis u spodní části menu', blank=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = 'Polední menu'
        verbose_name_plural = 'Polední menu'

def default_start_time():
        now = datetime.now()
        start = now.replace(hour=0, minute=0, second=0, microsecond=0)
        return start if start > now else start + timedelta(days=1)

class DailyProduct(models.Model):
    poledni_menu = models.ForeignKey(PoledniMenu, default=1)
    valid_for_date = models.DateTimeField('Platnost od', default=default_start_time, blank=True)
    name = models.CharField('Název', max_length=200 )
    amount = models.CharField('Množství', max_length=11, blank=True)
    price = models.CharField('Cena', default=0, max_length=14, blank=True)
    NONE = 0
    SOUP = 4 
    BIGFOOD = 5 
    STALE = 1
    WEEKLY = 2
    DAILY = 3
    TIME_CHOICES = (
        (STALE, 'Stálá nabídka'),
        (WEEKLY, 'Týdenní nabídka'),
        (DAILY, 'Denní nabídka'),
    )
    FOOD_CHOICES = (
        (NONE, '---'),
        (SOUP, 'Polévka'),
        (BIGFOOD, 'Hlavní jídlo'),
    )
    dtype = models.IntegerField('Nabídka', choices=TIME_CHOICES, default=DAILY)
    ptype = models.IntegerField('Typ', choices=FOOD_CHOICES, default=SOUP)
    def __unicode__(self):
        return self.name

jidelni_listek/views.py
# coding: utf-8
from django.shortcuts import get_object_or_404, get_list_or_404, render, redirect
from django.http import HttpResponse

from .models import Product, Type, List
# Create your views here.

def index(request):
    lists = get_list_or_404(List)
    return render(request, 'jidelni_listek/index.html', {
        'lists': lists,
    })

def detail(request, list_id):
    current_list = get_list_or_404(List, pk=list_id) 
    list_id = list_id
    current_list_name = current_list[0]
    products_by_type = Product.objects.filter(lists__id=list_id).all().order_by('product_type', 'product_order')

    return render(request, 'jidelni_listek/detail.html', {
        'current_list': current_list,
        'list_id': list_id,
        'current_list_name': current_list_name,
        'products_by_type' : products_by_type,
    })

jidelni_listek/templates/jidelni_listek/detail.html
{{ var|safe|escape }}
{% load staticfiles %}


<p>detail</p>
<p>{{ list.name }}</p>
<p>list id: {{ list_id }}
<p>id2: {{ products_by_type }}</p>
<br />
<ul>

{% for products in products_by_type.1 %}
	<li>{{ products.product_name}}</li>
{% endfor %}
</ul>
<ul>
{% for product in products_by_type %}
        {% ifchanged product.product_type.name %}
            <li><h3>{{ product.product_type.name }}</h3></li>
        {% endifchanged %}
	<li>{{ product.product_name }}</li>
{% endfor %}
</ul>

{% for current in current_list %}
                <li>{{ current.id }} : {{ current.name }} - {{ current.list_short_description }} > {{ current.types_in_list.name }}</li>
        {% endfor %}
</body>

jidelni_listek/templates/jidelni_listek/detail_list_1.html
{{ var|safe|escape }}
{% load staticfiles %}

{% for product in products_by_type.1 %}
        {% ifchanged product.product_type.name %}
	<tr class="danger">
            <th colspan="3">{{ product.product_type.name }}</th>
	</tr>
        {% endifchanged %}
	<tr>
	<td class="gramaz">{{ product.amount }}</td>
	<td class="nazev">{{ product.product_name }}</td>
	<td class="cena">{{ product.product_price }}</td>
	</tr>
{% endfor %}

jidelni_listek/templates/jidelni_listek/detail_list_2.html
{{ var|safe|escape }}
{% load staticfiles %}

{% for product in products_by_type.2 %}
        {% ifchanged product.product_type.name %}
	<tr class="danger">
            <th colspan="3">{{ product.product_type.name }}</th>
	</tr>
        {% endifchanged %}
	<tr>
		<td class="gramaz">{{ product.amount }}</td>
		<td class="nazev">{{ product.product_name }}</td>
		<td class="cena">{{ product.product_price }}</td>
	</tr>
			{% if list.special == True %}
				{% if product.plist %}
				<tr>
					<td colspan="3">Doporučené pivo: {{ product.plist }}
					<br />Doporučené víno: {{ product.vlist }}</td>
				</tr>
				{% endif %}
			{% endif %}
{% endfor %}

jidelni_listek/templates/jidelni_listek/detail_list_3.html
{{ var|safe|escape }}
{% load staticfiles %}

{% for product in products_by_type.3 %}
        {% ifchanged product.product_type.name %}
	<tr class="danger">
            <th colspan="3">{{ product.product_type.name }}</th>
	</tr>
        {% endifchanged %}
	<tr>
	<td class="nazev">{{ product.product_name }}</td>
	</tr>
			{% if list.experience == True %}
                                {% if product.plist %}
                                <tr>
                                        <td colspan="3">Doporučené pivo: {{ product.plist }}
                                        <br />Doporučené víno: {{ product.vlist }}</td>
                                </tr>
                                {% endif %}
                        {% endif %}
{% endfor %}

jidelni_listek/templates/jidelni_listek/detail_list_4.html
{{ var|safe|escape }}
{% load staticfiles %}

{% for product in products_by_type.4 %}
        {% ifchanged product.product_type.name %}
	<tr class="danger">
            <th>{{ product.product_type.name }}</th>
	</tr>
        {% endifchanged %}
	<tr>
	<td class="nazev">{{ product.product_name }}</td>
	</tr>
	{% for plist in product.plist.all %}
	<tr><td>Pivní degustace: {{ plist.product_name }}</td></tr> 
	{% endfor %}
	{% for vlist in product.vlist.all %}
	<tr><td>Vinná degustace: {{ vlist.product_name }}</td></tr>
	{% endfor %}
{% endfor %}

jidelni_listek/templates/jidelni_listek/detail_list_5.html
{{ var|safe|escape }}
{% load staticfiles %}

{% for product in products_by_type.5 %}
        {% ifchanged product.product_type.name %}
	<tr class="danger">
            <th colspan="3">{{ product.product_type.name }}</th>
	</tr>
        {% endifchanged %}
	<tr>
	<td class="gramaz">{{ product.amount }}</td>
	<td class="nazev">{{ product.product_name }}</td>
	<td class="cena">{{ product.product_price }}</td>
	</tr>
	<tr><td colspan=3>{{ product.product_description }}</td></tr>
{% endfor %}

jidelni_listek/templates/jidelni_listek/detail_list_6.html
{{ var|safe|escape }}
{% load staticfiles %}

{% for product in products_by_type.6 %}
        {% ifchanged product.product_type.name %}
	<tr class="danger">
            <th colspan="3">{{ product.product_type.name }}</th>
	</tr>
        {% endifchanged %}
	<tr>
	<td class="gramaz">{{ product.amount }}</td>
	<td class="nazev">{{ product.product_name }}</td>
	<td class="cena">{{ product.product_price }}</td>
	</tr>
{% endfor %}

jidelni_listek/templates/jidelni_listek/index.html
{% load staticfiles %}
<html lang="cs">
<head>
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" media="screen" />
	<link rel="stylesheet" type="text/css" href="{% static 'jidelni_listek/css/agency.css' %}" media="screen" />
 
</head>

<ul>
	
	{% for list in lists %}
        	<li><a href="{% url 'jidelni_listek:detail' list.id %}">{{ list.name }}</a></li>

		<ul>
		{% for product in list.sorted_products %}
			{% ifchanged product.product_type.name %}
			    <li><h3>{{ product.product_type.name }}</h3></li>
			{% endifchanged %}
			<li>{{ product.product_name }}</li>
		{% endfor %}
		</ul>


	{% endfor %}
    </ul>

jidelni_listek/templates/jidelni_listek/list_detail.html
{{ var|safe|escape }}
{% load staticfiles %}

{% if list_id == 1 %}

	{% for product in products_by_type.'list_id' %}
        	{% ifchanged product.product_type.name %}
        		<tr class="danger">
            			<th colspan="3">{{ product.product_type.name }}</th>
        		</tr>
        	{% endifchanged %}
        	<tr>
        		<td class="gramaz">{{ product.amount }}</td>
        		<td class="nazev">{{ product.product_name }}</td>
        		<td class="cena">{{ product.product_price }}</td>
        	</tr>
	{% endfor %}
{% endif %}

jidelni_listek/templates/jidelni_listek/lists.html
{% for list in lists %}
	    <div class="nabidka-modal modal fade" id="{{ list.id }}" tabindex="-1" role="dialog" aria-hidden="true">
		<div class="modal-content">
		    <div class="close-modal" data-dismiss="modal">
			<div class="lr">
			    <div class="rl">
			    </div>
			</div>
		    </div>
		    <div class="container">
			<div class="row">
			    <div class="col-lg-12">
				<div class="modal-body">
				    <!-- Project Details Go Here -->
				    <h2>{{ list.name }}</h2>
				    <p class="item-intro text-muted">{{ list.list_short_description }}</p>
				    <div class="bs-example" data-example-id="hoverable-table">
					<table class="table table-hover">
					{% for list_id, products in products_by_type.items %}
					 {% if list_id == list.id %}
					  {% for product in products %}

					    {% if list.experience %}
						{% ifchanged product.product_type.name %}
						<tr class="danger">
						    <th>{{ product.product_type.name }}</th>
						</tr>
						{% endifchanged %}
						<tr><td class="nazev">{{ product.product_name }}</td></tr>
						{% if product.plist %}
							<tr><td>Pivní degustace: {{ product.plist }}</td></tr> 
						{% endif %}
						{% if product.vlist %}
							<tr><td>Vinná degustace: {{ product.vlist }}</td></tr>
						{% endif %}
					    {% else %}
						{% ifchanged product.product_type.name %}
						<tr class="danger">
						    <th colspan="3">{{ product.product_type.name }}</th>
						</tr>
						{% endifchanged %}
						<tr>
						<td class="gramaz">{{ product.amount }}</td>
						<td class="nazev">{{ product.product_name }}</td>
						<td class="cena">{{ product.product_price }}</td>
						</tr>

						{% if list.special %}
							{% if product.plist %}
							<tr>
								<td colspan="3">Doporučené pivo: {{ product.plist }}
								<br />Doporučené víno: {{ product.vlist }}</td>
							</tr>
							{% endif %}
						{% endif %}
						{% if list.wine %}
							<tr><td colspan=3>{{ product.product_description }}</td></tr>
						{% endif %}
					    {% endif %}
					  {% endfor %}
					 {% endif %}
					{% endfor %}
					</table>
					<hr />
					<p class="bottom_line_description">{{ list.bottom_line_description }}</p>
				    </div>

				    <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Zavřít</button>
				</div>
			    </div>
			</div>
		    </div>
		</div>
	    </div>

{% endfor %}

jidelni_listek/templates/jidelni_listek/polednimenu.html
{{ var|safe|escape }}
{% load staticfiles %}

	<tr class="danger">
		<th colspan="3"><h5>Stálá nabídka</h5></th>
	</tr>
{% for product in poledni_menu_stale.1 %}
		<tr>
			<td class="gramaz">{{ product.amount }}</td>
			<td class="nazev">{{ product.name }}</td>
			<td class="cena">{{ product.price }}</td>
		</tr>

{% endfor %}
<tr class="danger">
                <th colspan="3"><h5>Týdenní nabídka</h5></th>
        </tr>
{% for product in poledni_menu_weekly.1 %}
                <tr>
                        <td class="gramaz">{{ product.amount }}</td>
                        <td class="nazev">{{ product.name }}</td>
                        <td class="cena">{{ product.price }}</td>
                </tr>

{% endfor %}
<tr class="danger">
                <th colspan="3"><h5>Denní nabídka</h5></th>
        </tr>
{% for product in poledni_menu_daily.1 %}
	
	
	{% ifchanged product.valid_for_date %}
	<tr class="danger">
		<th colspan="3"><h5>{{ product.valid_for_date | date:"l" }}</h5></th>
	</tr>
		{% endifchanged %}
		{% ifchanged product.ptype %}
		<tr>
			<th colspan="3">
			{% if product.ptype == 4 %}
			Polévka
			{% elif product.ptype == 5 %}
			Hlavní jídlo
			{% endif %}
			</th>
		</tr>
		{% endifchanged %}

		<tr>
			<td class="gramaz">{{ product.amount }}</td>
			<td class="nazev">{{ product.name }}</td>
			<td class="cena">{{ product.price }}</td>
		</tr>
	
{% endfor %}